comment:
  layout: "diff,flags,files,footer"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        flags:
          - unit
        paths:
          - "src"
