# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Checks

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15.0.1
      uses: actions/setup-java@v1
      with:
        java-version: 15.0.1
        java-package: jdk+fx
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build Jar
      run: ./gradlew --stacktrace -Pversion=${{ github.sha }} -PjavafxPlatform=linux jar

    - name: Run Checks
      run: ./gradlew --stacktrace -PjavafxPlatform=linux check
      
    - name: Run Coverage Report
      run: ./gradlew jacocoTestReport
    
    - name: Send to Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: build/reports/jacoco/test/jacocoTestReport.xml

