# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true

jobs:
  release:

    environment: deploy
    runs-on: ubuntu-latest
    env:
      INSTALL4J_DIR: "install4j/install4j9.0.5"

    steps:
      - uses: actions/checkout@v2
      
      - name: Check Version Tag
        id: tag_check
        run: |
          if [[ ${{ github.event.inputs.version }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=major_release::true
          fi

      - name: Set up JDK 17.0.1
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17.0.1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Checks
        run: ./gradlew --stacktrace -PjavafxPlatform=linux check
        env:
          JAVA_TOOL_OPTIONS: "-Dprism.verbose=true -Dprism.order=sw"

      - name: Download Install4j
        run: |
          mkdir -p "$HOME/install4j"
          curl https://download-gcdn.ej-technologies.com/install4j/install4j_unix_9_0_5.tar.gz -o "$HOME/install4j/install4j.tar.gz"
          tar xzf "$HOME/install4j/install4j.tar.gz" -C "$HOME/install4j"

      - name: Download Bundled JRE
        run: |
            mkdir -p "$HOME/.local/share/install4j/v9/jres"
            curl https://content.faforever.com/build/jre/windows-amd64-17.0.1.tar.gz -o "$HOME/.local/share/install4j/v9/jres/windows-amd64-17.0.1.tar.gz"

      - name: Build Windows Files
        run: |
          ./gradlew -Pversion="${{ github.event.inputs.version }}" \
          -PjavafxPlatform=win \
          -Pinstall4jHomeDir=$HOME/$INSTALL4J_DIR \
          -Pinstall4jLicense=${{ secrets.INSTALL4J_9_LICENSE }} \
          --info \
          --stacktrace \
          buildInstall4jMediaFiles

      - name: Build Linux Files
        run: |
          ./gradlew -Pversion="${{ github.event.inputs.version }}" \
          -PjavafxPlatform=linux \
          -Pinstall4jHomeDir=$HOME/$INSTALL4J_DIR \
          -Pinstall4jLicense=${{ secrets.INSTALL4J_9_LICENSE }} \
          --stacktrace \
          buildInstall4jMediaFiles

      - name: Get Artifact Paths
        id: artifact_paths
        run: |
          WINDOWS_EXE=$(ls build/install4j/faf_windows-x64_*.exe | head -n 1)
          WINDOWS_EXE_NAME=$(basename $WINDOWS_EXE)
          echo ::set-output name=WINDOWS_EXE::${WINDOWS_EXE}
          echo ::set-output name=WINDOWS_EXE_NAME::${WINDOWS_EXE_NAME}

      - name: Create Draft Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit: ${{ github.sha }}
          tag: v${{ github.event.inputs.version }}
          draft: true
          prerelease: ${{ steps.tag_check.outputs.major_release != 'true'}}
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: build/install4j/faf_*
          
      - name: Upload to Mirror
        if: steps.tag_check.outputs.major_release == 'true'
        uses: bayssmekanique/action-simple-file-upload@v1
        with:
          user: ${{ secrets.FTP_MIRROR_USERNAME }}
          password: ${{ secrets.FTP_MIRROR_PASSWORD }}
          host: ${{ secrets.FTP_MIRROR_HOST }}
          src: ${{ steps.artifact_paths.outputs.WINDOWS_EXE }}
          dest: ${{ steps.artifact_paths.outputs.WINDOWS_EXE_NAME }}

    
      
